-- ============================================================================
-- 014 — make the audit trail something a business could actually rely on.
--
-- Three problems this fixes:
--
-- 1. Step progress lived in completion_data under a magic "__steps_done" key,
--    in the same jsonb column as completion evidence. completeTask replaced
--    that column wholesale, so closing a task silently destroyed the step
--    history (and any evidence the invoicing webhook had written). The merge is
--    already fixed in code; this gives progress its own typed column so the two
--    can never collide again.
--
-- 2. task_events had no idea WHO did anything — no actor, no source. Every row
--    was implicitly "the owner".
--
-- 3. task_events was append-only by policy (no UPDATE/DELETE), but task_id was
--    ON DELETE CASCADE from business_tasks, and owners held `for all` on
--    business_tasks — which includes DELETE. So a user could delete a task and
--    cascade-wipe its entire history. An append-only log you can erase through
--    the back door is not evidence.
--
-- Idempotent and transactional.
-- ============================================================================

begin;

-- ---------- 1. step progress gets its own column ----------
alter table public.business_tasks
  add column if not exists steps_done int[] not null default '{}';

-- NOTE: the jsonb "__steps_done" key is deliberately NOT migrated or removed
-- here. The application still reads it, and because data.ts now fails loudly on
-- a read error, moving the data before the code cutover would break every task
-- page. This migration only PREPARES the column; the read/write cutover ships
-- as a code+migration pair once 014 is applied. That keeps 014 safe to apply
-- at any time, in any order.

-- ---------- 2. attribution + tamper-evident chain on the trail ----------
-- WHY THERE IS NO ip OR user_agent COLUMN, since an audit trail usually has
-- them: they are personal data, and collecting them here would need a lawful
-- basis, a retention window and a disclosure — in a product that ships a task
-- teaching users about תיקון 13 and that now implements erasure and retention
-- itself (017). What the evidence pack has to answer is "who did this, and can
-- the record be trusted", which actor_id + actor_kind + the hash chain answer
-- without retaining anyone's IP address indefinitely. Forensic repudiation
-- ("that login wasn't me") is an auth-layer question, and Supabase already logs
-- it there. If this is ever revisited, it needs a retention window in 017 and a
-- line in the privacy policy, not just two more columns.
alter table public.task_events add column if not exists actor_id uuid;
-- owner | system | integration
alter table public.task_events add column if not exists actor_kind text not null default 'owner';
alter table public.task_events add column if not exists prev_hash text;
alter table public.task_events add column if not exists hash text;

-- A chain needs an unambiguous order, and created_at cannot provide one:
-- now() is the TRANSACTION timestamp, so two events written in one transaction
-- share it exactly and the tie-break falls to a random uuid. The chain would
-- then be built in one order and verified in another, reporting tampering where
-- there was none — a false alarm on the one feature whose entire value is being
-- trustworthy. `seq` is monotonic and gap-tolerant, which is all that is needed.
alter table public.task_events
  add column if not exists seq bigint generated by default as identity;

create index if not exists task_events_chain_order_idx
  on public.task_events (business_id, seq);

-- Each row hashes its own content plus the previous row's hash, per business.
-- Rewriting or removing a row therefore breaks the chain from that point on,
-- which is what makes the log verifiable rather than merely append-only.
-- sha256() is built into Postgres 11+, so no extension is required.
create or replace function public.task_events_chain()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  prev text;
  payload text;
begin
  if new.actor_id is null then
    new.actor_id := auth.uid ();
  end if;

  -- Ordered by seq, not created_at: see the note on the column above.
  select e.hash into prev
    from public.task_events e
   where e.business_id = new.business_id
   order by e.seq desc
   limit 1;

  new.prev_hash := prev;

  -- seq is in the payload so a row cannot be silently re-ordered within the
  -- chain either. Column defaults are evaluated before BEFORE INSERT triggers
  -- fire, so new.seq is already assigned here.
  payload :=
    coalesce(prev, '') || '|' ||
    new.seq::text || '|' ||
    new.business_id::text || '|' ||
    coalesce(new.task_id::text, '') || '|' ||
    coalesce(new.template_id, '') || '|' ||
    coalesce(new.kind, '') || '|' ||
    coalesce(new.from_status, '') || '|' ||
    coalesce(new.to_status, '') || '|' ||
    coalesce(new.detail, '') || '|' ||
    coalesce(new.actor_kind, '') || '|' ||
    coalesce(new.actor_id::text, '') || '|' ||
    new.created_at::text;

  new.hash := encode(sha256(convert_to(payload, 'utf8')), 'hex');
  return new;
end
$$;

drop trigger if exists task_events_chain_tr on public.task_events;
create trigger task_events_chain_tr
  before insert on public.task_events
  for each row execute function public.task_events_chain();

-- ---------- 3. the trail must survive its task ----------
-- Owners keep read/insert/update on their tasks but lose DELETE, so the
-- ON DELETE CASCADE to task_events can no longer be triggered from a session.
-- (Nothing in the application deletes a business_task; account deletion goes
-- through the business row, where cascading the trail is the correct behaviour.)
drop policy if exists "business_tasks: owner all" on public.business_tasks;

drop policy if exists "business_tasks: owner read" on public.business_tasks;
create policy "business_tasks: owner read" on public.business_tasks
  for select using (
    exists (select 1 from public.businesses b where b.id = business_id and b.owner_id = auth.uid ())
  );

drop policy if exists "business_tasks: owner insert" on public.business_tasks;
create policy "business_tasks: owner insert" on public.business_tasks
  for insert with check (
    exists (select 1 from public.businesses b where b.id = business_id and b.owner_id = auth.uid ())
  );

drop policy if exists "business_tasks: owner update" on public.business_tasks;
create policy "business_tasks: owner update" on public.business_tasks
  for update using (
    exists (select 1 from public.businesses b where b.id = business_id and b.owner_id = auth.uid ())
  ) with check (
    exists (select 1 from public.businesses b where b.id = business_id and b.owner_id = auth.uid ())
  );

commit;
